### ISSUE TITLE
Possible Issue - Trailer without append

### ISSUE THREAD

**Issue by Ahsome** [airship-david/Trailer-Downloader#14]
When looking at the code for appending the name of the trailer, I noticed that if it is false, it simply saves as the filename

```python
if settings['append_filenames'] is not None and settings['append_filenames'].lower() == 'true':
            filename = arguments['title'].replace(':', '-')+' ('+arguments['year']+')-trailer.mp4'
        else:
            filename = arguments['title'].replace(':', '-')+' ('+arguments['year']+').mp4'
```

This is not inherently dangerous, because the code does check to see if a file like that exists (which it must, since we're giving the name of the trailer). However, it does mean when append is off its very likely no trailer will download, as it will have the same name as the movie

**Comment by airship-david** [comment]
Append filenames has been removed in v1.06 in favor of the new custom formatting option. It is still possible to choose formatting that matches the movie filename but, as you mentioned, this is not inherently dangerous and a user would have to set this up themselves for the problem to occur. Going to close this for now but we can reopen it if this becomes a problem.
