### ISSUE TITLE
Download_all does not enforce subfolder

### ISSUE THREAD

**Issue by Ahsome** [airship-david/Trailer-Downloader#18]
download_all does not use subfolder, even one is in settings.ini. This is currently it passes the variable **directory** to download.py, not **destination**, which is **directory+subfolder**

Easy fix, just need the pull requests to be done

**Comment by danz0l** [comment]
Are you sure ? I use a subfolder for each movie called Trailers, defined in
the settings.ini and that works ?

Maybe i hard coded it that way but I'm pretty sure it was just the filename
i hardcoded. And download_all works for 70% + of the time that way ?

**Comment by Ahsome** [comment]
Wait this works, even when you use download_all?

**Comment by Ahsome** [comment]
NEVERMIND, looks like download_all checks for subfolder, but does not actually use it, download still takes care of it

**Comment by danz0l** [comment]
Yes download_all passes everything to download
