### ISSUE TITLE
Issues with custom naming on latest build

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#24]
Having upgraded to latest stable there is an issue with the directory not getting created if defined.

python Trailer-Downloader/download_all.py --directory /media/z/Movies/1/                  Escape from Alcatraz (1979)
Traceback (most recent call last):
  File "/home/xxx/Trailer-Downloader/download.py", line 321, in <module>
    main()
  File "/home/xxx/Trailer-Downloader/download.py", line 259, in main
    for name in os.listdir(arguments['directory']):
OSError: [Errno 2] No such file or directory: '/media/z/Movies/1//Escape from Alcatraz (1979)/Trailers'

**Comment by danz0l** [comment]
My settings just defines sub directory as Trailers and filename as Trailer

**Comment by airship-david** [comment]
Looks like this was a bug with the new way existing trailers are being detected with any extension. The issue only appeared when the subfolder option was used. Fixed in v1.07.
