### ISSUE TITLE
1.07 HTML Parser

### ISSUE THREAD

**Issue by Tharic99** [airship-david/Trailer-Downloader#28]
Saw the 1.07 version is out, so I downloaded over my existing files, did NOT overwrite my settings.ini file. 

When attempting to use download.py or download_all.py, I'm getting No module named 'HTMLParser' errors.

Looks like it's included in the python file but it's not in the requirements.txt file?

**Comment by airship-david** [comment]
Ugh I'm assuming you're running Python 3 and everyone else is running 2.7? Looks like I should have tested Ahsome's unicode changes more. Going to have to tighten up on what makes it into releases. I'll have this fixed shortly. I'm not overly concerned with the settings.ini issue but maybe I'll make a workaround for that too.

**Comment by Tharic99** [comment]
Yep, I'm on Python 3. :)

**Comment by airship-david** [comment]
This issue has been fixed. Should now work with both python 2 and 3. Included an example version of settings.ini so nothing gets overwritten but you still get a current copy.
