### ISSUE TITLE
Any chance of Trailer Folder support ?

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#3]
Brilliant script and seems to work well although incredibly slow downloading from Apple trailers.

Do to the fact i have lots of extras nested in their appropriate folders under the movie folder for Plex is there anyway to support the Trailers folder or a way to modify the script to do that ?

**Comment by airship-david** [comment]
Support for subfolders has been added :). You can set the name of the subfolder you would like to use in the settings.ini file. 

Downloading the trailers from Apple is a bit slow (especially if you choose 1080p) but this hasn’t been a big deal on my end and I still prefer the quality so I haven’t attempted to find a workaround. All suggestions are welcome.

Cheers!

**Comment by danz0l** [comment]
Hi David. Not sure if this email will get to you or whether i have to do
this git.

Brilliant script btw, and I'm loving it so far. Really helping a great deal.

Thanks for adding sub folders too, i looked at the code and could have
hacked it a little to my needs but then it would be broken on any updates
you bring to it.

On that note can we have support for trailer naming ? I know you take the
movie name as the main lead and apoend --trailer to it but i like to keep
my trailers simple. So in a sub directory of the movie i have a folder
called Trailers and within a trailer.mkv file. I just think, for me, it
presents itself better with Plex. Again u can hard hack your code but I'd
prefer not to do that.

Also I've had no success as yet automating with tautilli or radarr. Have
you got the script automated in any way ?

I just want to thank you for a very reliable, very robust script that does
everything i was hoping to and then some.

Btw have you thought about incorporating HD-trailers.net ????

Keep up the good work mate and anything i can do to help, just ask

**Comment by airship-david** [comment]
Awesome! Glad this script helped you out. I've had great success with it and I needed something to replace the trailer addict plugin when that went down. If you could star the project, I would appreciate it. This script consistently gets a lot of downloads but I haven't received much support from the community.

For the trailer naming, I believe that is the way it is currently working. Are you saying you would prefer the files to not have "-trailer" appended to them? If you could elaborate a bit on how you would like the naming to be different, I can take a look at it.

As for the automation, I have this 100% automated with Tautulli to download a trailer whenever a new movie is added to Plex. Please take a look at those instructions again and make sure you follow each of the steps exactly and it should work. If something isn’t clear in those instructions, let me know and I can revise that part somewhat.

I haven’t looked at adding hd-trailers.net or traileraddict.com yet but that may be something I try to incorporate in the future. I simply chose Apple Trailers and TMDB out of personal preference.

**Comment by danz0l** [comment]
Hi David

That's a shame that the community isn't more supportive, i know only too
well how disheartening it can be getting lots of downloads without any
communication.

Yes if you use a Trailers sub folder in Plex within the movie folder, you
don't need the --trailer part of the filename. As i add many extras to each
of my movies using sub folders in the Plex naming convention, i rename my
trailer files to just say "Trailer.mkv" within that sub Trailer directory.
Then when it's presented in Plex that trailer simply shows as Trailer under
the extras part of the movie alongside Featurettes, Interviews, Deleted
Scenes, Shorts etc. It just keeps things simple and a very quick easy way
to separate trailers from the other parts of the extras.

I did try following the instructions you had in Tautilli and i did struggle
with a part of its understanding, hence the automation part isn't working
for me currently. I'll have another look at it today though and try and
work out what wasn't clear. I think it was to do with only firing the
script on movie import but having tried to do this through my phone i think
i struggled to find that option.

As i said, if i can be of any help whatsoever, then please feel free to
ask.

I'll look to understand the code better and see if incorporating
trailerhd.net downloading is viable although if I'm honest you've really
covered most sceneries with Apple and YouTube. I've actually been quite
amazed how accurate your matching is.

I'll also look to see if i can automate this script through Radarr when i
get time, and if it's doable I'll try and write a how to for you to
incorporate on your github ? I think most people use radarr these days and
as that would fire before Tautilli i personally think that works better for
most (and would certainly generate much more interest in your script
because not everybody will use Tautilli).

**Comment by airship-david** [comment]
Ok I added an option to the settings.ini file called "append_filenames." If you set that to false, "-trailer" will no longer be appended to the filenames :).

I think figuring out a way to use this script in conjunction with Radarr is a great idea. Let me know if you come up with a good way to do so and I will definitely add that to the instructions. 

Also let me know if you think of any other ways to improve the script and I will try to look into it. Thanks!
