### ISSUE TITLE
Tautulli in Docker

### ISSUE THREAD

**Issue by PatB1023** [airship-david/Trailer-Downloader#37]
First of all, thank you sir. Plex is hit or miss with the trailers. This helps a lot.

I am a noob so this is to help others out there. If you are running Tautulli in docker, you have to install in the Tautulli dir. 

I just navigated to the dir and then used this command:
sudo -H pip install -r /path/to/scripts/requirements.txt -t .

If you get pip command not found, use this command first:
sudo apt-get install python-pip

You will also have to map your media folder in the tautulli container.

Awesome job.

**Comment by airship-david** [comment]
Thanks for the tip! I will add this to the instructions. 

Another tip: if you would like to place the scripts outside the Tautulli config directory you can attach the directory to the Tautulli container like in the example below. Cheers!

```
-v /path/to/scripts:/scripts

docker run --privileged --name tautulli --restart=always \
  -p 8181:8181 \
  -v /path/to/config:/config \
  -v /path/to/logs:/logs \
  -v /path/to/scripts:/scripts \
  linuxserver/tautulli;
```

**Comment by airship-david** [comment]
Docker notes have been added to the README. Closing this for now but we can reopen it if additional changes are needed.
