### ISSUE TITLE
Nothing happen! Debug?

### ISSUE THREAD

**Issue by sasagr** [airship-david/Trailer-Downloader#42]
Hi. I there any way to debug it?
I just installed it and run it but I get nothing in return, no error, no trailer

pi@raspberrypi:~/Trailer-Downloader $ python3 download.py --title "A Rainy Day in New York" --year "2019" --directory "/mnt/GD/Movies/A Rainy Day in New York (2019)"
pi@raspberrypi:~/Trailer-Downloader $

Also the line to install the requirements should not be with pip3, otherwise the later python3 command wont find the dependencies that are installed in py2 folder
sudo -H pip install -r requirements.txt

**Comment by airship-david** [comment]
Hello! I have fixed the installation instructions in v1.10. Looks like that didn't get updated properly when switching over to the python 3 requirement. Sorry about that! Unfortunately the current version of this project does not include a verbose option but that is being added to the next version. Were you able to get this working? I would need some sort of error you're seeing in order to help out.

**Comment by sasagr** [comment]
Hi. Thanks for the update. Yes I managed to make it working. Don't remember how but now when it founds a movie it gives as output the name of the movie and the trailer is downloaded aside the movie file. It seems all be working fine but -v (verbose) option would be really great. I m running your script in crontab and writing the output in a log file. Having a richer output would help me to see what's going on. Maybe some basic (no verbose) output showing success and source of trailer or no trailer found would be maybe even enough. Up to you ! thanks anyway

**Comment by sasagr** [comment]
I have just noticed that you added the radarr and tautulli options.. This is great, I did not have them in my previous version and by the way I could not git pull to get them. I got some error. I had to reinstall it all again a just recopy my older settings file.
At this point if you have radarr/tautulli integration maybe it could be better to have a log file created in the folder? I won't use the script anymore if radarr connection works fine

**Comment by airship-david** [comment]
Adding some basic output for the result is reasonable. I'll get that added in today. The error you got on the git pull was resolved v1.10 so that shouldn't occur on future releases (settings.ini is no longer tracked). I don't think adding in a log file currently makes sense for the project but if some output for the result is added in you should be able to monitor the Radarr log files.

**Comment by sasagr** [comment]
That's sound great! 
At the moment I m facing an issue with radarr running on a seedbox:
Unable to send OnDownload notification to: Trailer-Downloader: ApplicationName='/home32/sasagr/Trailer-Downloader/download_radarr.py', CommandLine='', CurrentDirectory='', Native error= Access denied

It seems to be a permission error, though I have no issues to run the script from command line. I open a ticket with seedbox support. 
Mentioning the issue here is case you have a clue.

**Comment by sasagr** [comment]
the download_radarr.py needed to be executable but now I see on radarr log:
"/usr/bin/env: 'python3' : No such file or directory"

I checked the and /usr/bin/env is resent in the seedbox structure

**Comment by airship-david** [comment]
The result of the download has been added to v1.11. In general, you can solve permission issues on anything by using "chmod 777 -R /path/to/folder". If python3 is not installed, you'll need to install it. That being said, these issues are outside of the scope of this project.

**Comment by war3zlod3r** [comment]
> the download_radarr.py needed to be executable but now I see on radarr log:
> "/usr/bin/env: 'python3' : No such file or directory"
> 
> I checked the and /usr/bin/env is resent in the seedbox structure

Sorry to resurrect a dead thread but did you get a resolution on this issue having the same problem

**Comment by sasagr** [comment]
> > the download_radarr.py needed to be executable but now I see on radarr log:
> > "/usr/bin/env: 'python3' : No such file or directory"
> > I checked the and /usr/bin/env is resent in the seedbox structure
> 
> Sorry to resurrect a dead thread but did you get a resolution on this issue having the same problem

No. I never managed to have a custom scripts (and not only this) working on radarr/sonarr installed on a seedbox and since also sb support cannot help, I gave up. :(
My solution is at the moment to have a custom script executed in crontab that checked frequently if any movie has been added to a temporary folder and if positive it will run Trailer-Downloader to add trailer before moving it to my main storage.
