### ISSUE TITLE
Tmdbsimple not installed

### ISSUE THREAD

**Issue by The-Kid-Gid** [airship-david/Trailer-Downloader#43]
I'm not sure if this is a problem with the script or my being an idiot, but I cloned the repository with `git clone *URL*` and used the provided pip command to install the required packages, however when I tried to download a trailer for a specific movie I got `ERROR: tmdbsimple is not installed.` Running `pip freeze` returns 
`asn1crypto==0.24.0
certifi==2019.11.28
chardet==3.0.4
configparser==3.5.0b2
cryptography==2.6.1
dbus-python==1.2.12
entrypoints==0.3
enum34==1.1.6
ffmpeg==1.4
idna==2.8
ipaddress==1.0.17
keyring==18.0.1
keyrings.alt==3.1.1
pycrypto==2.6.1
PyGObject==3.34.0
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.12.0
tmdbsimple==2.2.0
Unidecode==1.1.1
urllib3==1.25.8
youtube-dl==2020.1.15`
Clearly, tmdsimple is installed, but I have no idea what I have done wrong.

**Comment by airship-david** [comment]
It sounds like I left some bad instructions in the README after switching over to the python 3 requirement. I’ll get that updated. Try installing the requirements like below.

```
sudo python3 -m pip install -r requirements.txt
```

**Comment by The-Kid-Gid** [comment]
Thank you! It now works perfectly.
