### ISSUE TITLE
cannot update from repo

### ISSUE THREAD

**Issue by sasagr** [airship-david/Trailer-Downloader#49]
I cannot update from repo

pi@raspberrypi:~/Trailer-Downloader $ sudo git pull
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 68 (delta 39), reused 45 (delta 23), pack-reused 0
Unpacking objects: 100% (68/68), done.
From https://github.com/airship-david/Trailer-Downloader
   875ae3e..f25df2d  master     -> origin/master
   b8f5293..6259a2e  develop    -> origin/develop
 * [new tag]         v1.11      -> v1.11
 * [new tag]         v1.10      -> v1.10
Updating 875ae3e..f25df2d
error: Your local changes to the following files would be overwritten by merge:
        download.py
        settings.ini
Please commit your changes or stash them before you merge.
Aborting
pi@raspberrypi:~/Trailer-Downloader $

**Comment by airship-david** [comment]
There isn't enough to go off of here for me to help with anything and this works for me with no issues. If you're having issues doing a git pull on any project, you can just delete the repo and clone again. I would recommend doing that.
