### ISSUE TITLE
Using download_all.py crashes if a movie doesn't have a year listed in themoviedb.org and youtube extractor errors

### ISSUE THREAD

**Issue by war3zlod3r** [airship-david/Trailer-Downloader#54]
I also occasionally get another error that shows up in this log.

[Script Output](https://pastebin.com/iMVHrYr4)

**Comment by airship-david** [comment]
The issue with the missing year should be resolved in v1.12. Our hands are sort of tied on the youtube-dl error because it is an external package but you should head over to their github page and create an issue.
