### ISSUE TITLE
RequestsDependencyWarning

### ISSUE THREAD

**Issue by sasagr** [airship-david/Trailer-Downloader#56]
I m not sure there is something you can do but recenttly I m getting this when the script is downloading a trailer. It appears to be a warning only since the trailer is downloaded successfully.

/.local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.19.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)

**Comment by airship-david** [comment]
Have you tried updating python and the requests package? This issue is not related to this project.
