### ISSUE TITLE
Radarr script not working, at least on Linux

### ISSUE THREAD

**Issue by Garmatant** [airship-david/Trailer-Downloader#58]
Hi. Thanks so much for these scripts! I had to make two changes to download_radarr.py to get it to work for me. Perhaps these changes are not required on Windows. I can't say. I'm using Ubuntu 18.04.

After line 37, add:
```
    arguments['file']+='/'
```

On line 43, change:
```
        if not os.path.isfile(arguments['file']):
```
to:
```
        if not os.path.isdir(arguments['file']):
```

Dave.

**Comment by The-Kid-Gid** [comment]
I am not the project admin, just a user, but maybe make a PR with the changes?

**Comment by Garmatant** [comment]
Ok, will do.
