### ISSUE TITLE
Language do not work

### ISSUE THREAD

**Issue by syralk** [airship-david/Trailer-Downloader#64]
Hi when I change the language it is still downloading the english one.

**Comment by airship-david** [comment]
Please provide examples. The language code is only for TMDB if I’m remembering right. Apple doesn’t provide trailers in anything other than the original language and most of the trailers tagged as being in a different language on TMDB actually aren’t so this is a difficult problem to overcome.

**Comment by syralk** [comment]
So if I look at TMDB api 
https://api.themoviedb.org/3/movie/500919/videos?api_key=<<api key>>&language=fr
I can see the trailer is the french one

but if I use the setting FR and download the trailer im getting the english one
python3 download.py --title "211" --year "2018" --directory "path/to/folder/211 (2018)"
Setting are
# ISO 3166-1 Region Code:
region = FR

# Language Code:
lang = fr

**Comment by airship-david** [comment]
Thanks for that! I rolled out a fix on the develop branch. Now when you select a language other than English it will disable Apple downloads entirely and only use what is available on TMDB. Please check out the develop branch and let me know if that resolved the issue.

**Comment by syralk** [comment]
it work great thanks :)
