### ISSUE TITLE
Trailers not being found on TMDB

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#66]
As per title, on the latest build its no longer finding movie trailers for download on the TMDB

**Toy Story 4 (2019)
SUCCESS: Trailer downloaded.
Toy Story (1995)
ERROR: No trailer found.**

I checked my API and its right, i also tried this

**python3 download.py --title "Toy Story" --year "1995" --directory ~/Trailer-Downloader/
ERROR: No trailer found.**

Checking youtube_dl its at the latest version

**sudo pip3 install --upgrade youtube-dl
Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.8/dist-packages (2020.5.8)**

**Comment by danz0l** [comment]
Tried updating to latest versions of

requests
tmdbsimple
unidecode

Still the same issue

Videos from apple download fine.

**Comment by danz0l** [comment]
ok so i rolled back to a previous cloned version with the same issues. So looked deeper. In the downloads directory within then script.

Trailer.f264
Trailer.f137
Trailer.f136
Trailer.f134

all mp4s and play perfectly so seems to be an issue with copying them across.

**Comment by danz0l** [comment]
Checked permissions and everything seems fine, can copy files from the scripts download folder just fine, but to be sure, even tried running the script with sudo, same issue.

**Comment by airship-david** [comment]
Hey @danz0l I haven't been able to replicate this issue yet but it does sound related to permissions or youtube-dl or maybe even ffmpeg since youtube-dl relies on it. Youtube-dl downloads each video in multiple segments ending with .f264, .f137, .f136, and etc. before merging them all together in the downloads folder. The script then moves the merged file to the directory you specify. It doesn't seem like youtube-dl is getting past merging the segments together.

**Comment by danz0l** [comment]
is there anything i can do to help test ?

**Comment by airship-david** [comment]
Just out of curiosity, what version do you get for ffmpeg?
```
ffmpeg -version
```

**Comment by danz0l** [comment]
ah didn't even realise that youtube_dl relied on ffmpeg and this was a fresh install of Ubuntu Server 20.04 LTS. Installed the script dependancies but ffmpeg isn't installed by default. Did that and BAM up it went and started downloading.

Thanks as always mate and handy to know for future reference. Maybe include that requirement somewhere in the docs just incase ? 

Keep up the excellent work :)

**Comment by airship-david** [comment]
Glad that sorted it out! I will add ffmpeg to the requirements.txt file. I thought it was already in there for some reason.
