### ISSUE TITLE
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

### ISSUE THREAD

**Issue by jasonmotec** [airship-david/Trailer-Downloader#7]
Thanks for a great and excellent program, works a treat... 

On the movie, Replicas (2018)
I get this error message after 30 seconds - ERROR: Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

I looked at the downloads folder, and it contains these 3 files:
Replicas (2018)-trailer.f398.mp4   - 8,246 KB
Replicas (2018)-trailer.mp4.f140   - 1,431 KB
Replicas (2018)-trailer.temp.mp4  - 1 KB

Also, besides the above movie with that error message, out of over 300 movies, with a success rate of 98% I have just noticed another bug every time the script is run.
These 6 movies appear one after the other with a 10 second interval between them, but no trailers are actually downloaded... 

The Upside (2017)
Dragged across concrete (2018)
Meg (2018)
Sicario 2 Soldado (2018)
Robin Hood Origins (2018)
Professor Marston & the Wonder Women (2017) 

Every time the script is run in SSH, the above appear, one after the other, but no trailers are downloaded.

Apart from that, love this program and its exactly what I have been looking for!

**Comment by airship-david** [comment]
Hey thanks! Please be sure to star the project if you like it. Support is always appreciated. I will check into the issue you’re seeing with the Replicas trailer. For all of the other trailers you mentioned, the issue is that they are mislabeled. If you look up each of those movies on TMDB, you’ll see that either the year or the title is incorrect for each of them. This issue will be uncommon if you are using a program like Radarr. Basically it is searching for each of those films but it cannot find any matching results. Eventually I may add a verbose option to the script that makes this more clear.

**Comment by jasonmotec** [comment]
Thank you for your quick reply 👍 
I have added a star to this amazing project!!!

Yes - you were spot on, I found the issue with the naming of the folders - and you were right, I use a program called Radarr.

The Upside (2017) - change the year to '2019' 
Dragged across concrete (2018) - change the year to '2019'
Meg (2018) - added 'The' at the front
Sicario 2 Soldado (2018) - renamed to "Sicario Day of the Soldado (2018)"
Robin Hood Origins (2018) - removed 'Origins'
Professor Marston & the Wonder Women (2017) - replaced '&' with 'and'

Once I did the above, it worked well - detected and downloaded the Trailers for the above.

It's only the 'Replicas' trailer with that error.

That would be great if you add a verbose option to the script!

**Comment by airship-david** [comment]
Awesome! Glad that sorted it out. I’ll check into that issue with the Replicas trailer tomorrow and get back to you 👍

**Comment by airship-david** [comment]
I checked into that Replicas trailer and it was downloaded to my machine without any issues. Is it possible that you are running an old version of ffmpeg? I would suggest updating that first. If that doesn't work, ffmpeg might be missing a codec.

**Comment by jasonmotec** [comment]
This is really unusual - especially when it only occurs on this particular movie.

If this makes a difference:
I have it up and running on a Synology DS116 NAS running the latest DiskStation 6.1
I use Emby to manage my library
Appears to have Python 2.7 installed

I have even just installed the ffmpeg 4.1-11 from the package center within DiskStation, but that did not make a difference.

Everything works well, except for this particular movie.

When I type: 
pip install ffmpeg

I get the this message:
Requirement already satisfied: ffmpeg in /usr/lib/python2.7/site-packages (1.4)


If I type:
ffmpeg -version

This comes up as my version:
ffmpeg version 2.7.1 Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.3 (crosstool-NG 1.20.0) 20150311 (prerelease)
configuration: --prefix=/usr --incdir='${prefix}/include/ffmpeg' --arch=arm --target-os=linux --cross-prefix=/usr/local/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi- --enable-cross-compile --enable-optimizations --enable-pic --enable-gpl --enable-shared --disable-static --enable-version3 --enable-nonfree --enable-libfaac --enable-encoders --enable-pthreads --disable-bzlib --disable-protocol=rtp --disable-muxer=image2 --disable-muxer=image2pipe --disable-swscale-alpha --disable-ffserver --disable-ffplay --disable-devices --disable-bzlib --disable-altivec --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libmp3lame --disable-vaapi --disable-decoder=amrnb --disable-decoder=ac3 --disable-decoder=ac3_fixed --disable-encoder=zmbv --disable-encoder=dca --disable-encoder=ac3 --disable-encoder=ac3_fixed --disable-encoder=eac3 --disable-decoder=dca --disable-decoder=eac3 --disable-decoder=truehd --cc=/usr/local/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-ccache-gcc --enable-yasm --enable-libx264 --enable-encoder=libx264
libavutil      54. 27.100 / 54. 27.100
libavcodec     56. 41.100 / 56. 41.100
libavformat    56. 36.100 / 56. 36.100
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 16.101 /  5. 16.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.100 /  1.  2.100
libpostproc    53.  3.100 / 53.  3.100

Is there any other way I get this working.

**Comment by airship-david** [comment]
The version of ffmpeg you are running (2.7.1) is quite old so that is likely the issue.  If you already installed 4.1.11, my guess is that your path needs to be updated to point to the new version instead of the old one. If you type "which ffmpeg" on the command line you'll find where the 2.7.1 version is installed. You'll just need to figure out where the 4.1.11 version is installed and update your path to point to that version instead.

**Comment by airship-david** [comment]
Also, be sure to add the path of the new version of ffmpeg to the settings.ini file.

**Comment by jasonmotec** [comment]
Thank you so much, it worked!!!
I changed the path to "ffmpeg_path = /volume1/@appstore/ffmpeg/bin/ffmpeg" in settings.ini file

I noticed that I get this repeated 16 times under Replicas (2018):
/bin/cp: cannot create regular file ‘/tmp/synoproxy.conf’: Permission denied

**Comment by airship-david** [comment]
Awesome glad I could help 👍. I don’t have any experience with synology so I can’t be of much help there. The script copies the downloaded trailer to the movie folder so there must be some sort of issue with permissions occurring along the way.

**Comment by jasonmotec** [comment]
All good :) its probably something minor!

Thank you so much for helping me with this!!!
