### ISSUE TITLE
Do you mind if I steal some code from you?

### ISSUE THREAD

**Issue by jsaddiction** [airship-david/Trailer-Downloader#72]
Good afternoon.  I am practicing my python skills and have modified your code and added some extra functionality.  Still heavily under construction.  I would like to put my version up for peer review once its completely written and tested.  I am asking your permission to redistribute said code here on github.  Of course I will link to and provide proper thanks to your efforts on this as the core functionality is based around your work.  If you would rather not please advise and I will make the repo private.  Thank you for your time and consideration!

[My Repo](https://github.com/jsaddiction/Trailer-Technician)

**Comment by The-Kid-Gid** [comment]
This project is licensed under the [GNU GPL v3.0](https://choosealicense.com/licenses/gpl-3.0/). As a courtesy, it is advisable that you credit the original project, but there are no restrictions on your use of it as long as you license your fork under the GPL or a GPL-equivalent license.

**Comment by airship-david** [comment]
No worries @jsaddiction! Feel free to use any part of this project however you wish. Appreciate you checking!
