### ISSUE TITLE
Problems using Tautulli

### ISSUE THREAD

**Issue by joreilly02** [airship-david/Trailer-Downloader#73]
Setting up the Tautulli script, I'm getting the following error.  Any idea how to fix?   

Tautulli Notifiers :: Script returned: 
    [91mERROR:[0m requests is not installed. 
    [91mERROR:[0m download.py not found

I'm using macOS Catalina.    Thanks!

**Comment by tehniemer** [comment]
Looks like you don't have the dependencies installed and Tautulli isn't pointed to the correct location of the script.

**Comment by airship-david** [comment]
Sorry for the delay @joreilly02. @tehniemer is correct. You need to install the requirements first.
