### ISSUE TITLE
Question about CRON

### ISSUE THREAD

**Issue by tehniemer** [airship-david/Trailer-Downloader#74]
How does this script work if it's set up as a CRON job to run `python3 download_all.py --directory "/path/to/movies"` daily? Will it re-download every trailer or will it skip directories that already have a trailer?

**Comment by airship-david** [comment]
Hi @tehniemer. When you run any of these scripts, including download_all.py, they will skip downloading trailers that already exist in the directory.

**Comment by tehniemer** [comment]
That's great news! Thanks for the prompt reply.
