### ISSUE TITLE
download_all Permission Denied error

### ISSUE THREAD

**Issue by Tharic99** [airship-david/Trailer-Downloader#8]
Hi David,

First off, fantastic tool. Great work!

I'm able to get it to work fine using just download.py. However, when I run the download_all.py, I get Permission Denied errors.

I'm running on Ubuntu 18. I have both Python 2.7 and Python 3.6 installed. However, my tools are pointing to Python 3.6 for this.

In my settings.ini file, I have modified my python path to be:
python_path = /usr/local/lib/python3.6

That's the folder where the dist_packages folder exists that has tmdbsimple, ffmpeg and youtube-dl. 

For me, I use 

<code>python3 ~/downloads/trailer/download.py --title "xxxx" --year "2018" --directory "/mnt/xxxx"</code>

for my download.py to work and it works fantastic.

However when I execute 

<code>python3 ~/downloads/trailer/download_all.py --directory "/mnt/xxxx"</code>

I can see it parse through my movie folders, but on every single one I get an error of:

<code> sh: 1: /usr/local/lib/python3.6: Permission denied</code>

I have ownership of the /usr/local/lib/python3.6 folder and I've run it as sudo. Plus I've already granted the ~/downloads/trailer/download.py file u+x permissions, so it can execute however I'm still seeing the error. I was tempted to modify your <code>download_all.py></code> file and hardcode the <code>python3 ~/downloads/trailer/download.py</code> portion in myself, but I couldn't decipher the <code>os.system(settings['python_path']+' '+os.path.split(os.path.abspath(__file__))[0]+'/download.py --title "'+title+'" --year "'+year+'" --directory "'+directory+'"'</code> portion unfortunately. My python skills are non-existent unfortunately.

Any ideas?

**Comment by airship-david** [comment]
Hello! Sorry for the delayed response. The way that the download_all.py script calls the download.py script is a bit bizarre but that script was sort of an afterthought and I wanted to keep the code compartmentalized. So this is just a guess but what path do you get when you run "which python3"? This is the path that you will need to use for the python_path variable. My guess is that the correct path is something like "/usr/local/bin/python3".

**Comment by Tharic99** [comment]
Awesome! That resolved the issue. I've got a few other questions/suggestions but I'll drop them on a different issue.

Thank you!
