### ISSUE TITLE
Suggestion - Check if trailer exists in the folder already?

### ISSUE THREAD

**Issue by Tharic99** [airship-david/Trailer-Downloader#9]
So I'm curious if it's possible to implement a change that checks to see if the trailer file already exists in a folder? if it does, then the process simply skips downloading the trailer. Currently it seems like it downloads the trailer file again and overwrites the existing file. 

Doing this type of check would let me essentially run the download_all process on a weekly schedule basis to ensure my trailers are all in place but not having to download the same ones again and again and again.

Thanks for a great app!

**Comment by danz0l** [comment]
Think that is already implemented. Tells me it's found a trailer already and skips. Just wish it would check for other extensions like mkv so u don't end up with 2 trailers in my trailer directory

**Comment by airship-david** [comment]
Hello! Yes checking if the file already exists and skipping it is already included. I can look into adding the ability to check for multiple extensions sometime as well. Glad this is working for you! I’ve had an awesome success rate with it running on my server and I thought others might find it useful as well.

**Comment by airship-david** [comment]
This is resolved in v1.06.
